var files_map = {
  "Ascension Island": "Ascension_Island.png",
  "Andorra": "Andorra.png",
  "United Arab Emirates": "United_Arab_Emirates.png",
  "Afghanistan": "Afghanistan.png",
  "Antigua and Barbuda": "Antigua_&_Barbuda.png",
  "Anguilla": "Anguilla.png",
  "Albania": "Albania.png",
  "Armenia": "Armenia.png",
  "Angola": "Angola.png",
  "Antarctica": "Antarctica.png",
  "Argentina": "Argentina.png",
  "American Samoa": "American_Samoa.png",
  "Austria": "Austria.png",
  "Australia": "Australia.png",
  "Aruba": "Aruba.png",
  "\u00c5land Islands": "\u00c5land_Islands.png",
  "Azerbaijan": "Azerbaijan.png",
  "Bosnia and Herzegovina": "Bosnia_&_Herzegovina.png",
  "Barbados": "Barbados.png",
  "Bangladesh": "Bangladesh.png",
  "Belgium": "Belgium.png",
  "Burkina Faso": "Burkina_Faso.png",
  "Bulgaria": "Bulgaria.png",
  "Bahrain": "Bahrain.png",
  "Burundi": "Burundi.png",
  "Benin": "Benin.png",
  "St. Barth\u00e9lemy": "St._Barth\u00e9lemy.png",
  "Bermuda": "Bermuda.png",
  "Brunei": "Brunei.png",
  "Bolivia": "Bolivia.png",
  "Caribbean Netherlands": "Caribbean_Netherlands.png",
  "Brazil": "Brazil.png",
  "Bahamas": "Bahamas.png",
  "Bhutan": "Bhutan.png",
  "Bouvet Island": "Bouvet_Island.png",
  "Botswana": "Botswana.png",
  "Belarus": "Belarus.png",
  "Belize": "Belize.png",
  "Canada": "Canada.png",
  "Cocos (Keeling) Islands": "Cocos_(Keeling)_Islands.png",
  "Congo - Kinshasa": "Congo_-_Kinshasa.png",
  "Central African Republic": "Central_African_Republic.png",
  "Congo - Brazzaville": "Congo_-_Brazzaville.png",
  "Switzerland": "Switzerland.png",
  "C\u00f4te d'Ivoire": "C\u00f4te_d\u2019Ivoire.png",
  "Cook Islands": "Cook_Islands.png",
  "Chile": "Chile.png",
  "Cameroon": "Cameroon.png",
  "China": "China.png",
  "Colombia": "Colombia.png",
  "Clipperton Island": "Clipperton_Island.png",
  "Costa Rica": "Costa_Rica.png",
  "Cuba": "Cuba.png",
  "Cape Verde": "Cape_Verde.png",
  "Cura\u00e7ao": "Cura\u00e7ao.png",
  "Christmas Island": "Christmas_Island.png",
  "Cyprus": "Cyprus.png",
  "Czechia": "Czechia.png",
  "Germany": "Germany.png",
  "Diego Garcia": "Diego_Garcia.png",
  "Djibouti": "Djibouti.png",
  "Denmark": "Denmark.png",
  "Dominica": "Dominica.png",
  "Dominican Republic": "Dominican_Republic.png",
  "Algeria": "Algeria.png",
  "Ceuta and Melilla": "Ceuta_&_Melilla.png",
  "Ecuador": "Ecuador.png",
  "Estonia": "Estonia.png",
  "Egypt": "Egypt.png",
  "Western Sahara": "Western_Sahara.png",
  "Eritrea": "Eritrea.png",
  "Spain": "Spain.png",
  "Ethiopia": "Ethiopia.png",
  "European Union": "European_Union.png",
  "Finland": "Finland.png",
  "Fiji": "Fiji.png",
  "Falkland Islands": "Falkland_Islands.png",
  "Micronesia": "Micronesia.png",
  "Faroe Islands": "Faroe_Islands.png",
  "France": "France.png",
  "Gabon": "Gabon.png",
  "United Kingdom": "United_Kingdom.png",
  "Grenada": "Grenada.png",
  "Georgia": "Georgia.png",
  "French Guiana": "French_Guiana.png",
  "Guernsey": "Guernsey.png",
  "Ghana": "Ghana.png",
  "Gibraltar": "Gibraltar.png",
  "Greenland": "Greenland.png",
  "Gambia": "Gambia.png",
  "Guinea": "Guinea.png",
  "Guadeloupe": "Guadeloupe.png",
  "Equatorial Guinea": "Equatorial_Guinea.png",
  "Greece": "Greece.png",
  "South Georgia and South Sandwich Islands": "South_Georgia_&_South_Sandwich_Islands.png",
  "Guatemala": "Guatemala.png",
  "Guam": "Guam.png",
  "Guinea-Bissau": "Guinea-Bissau.png",
  "Guyana": "Guyana.png",
  "Hong Kong SAR China": "Hong_Kong_SAR_China.png",
  "Heard and McDonald Islands": "Heard_&_McDonald_Islands.png",
  "Honduras": "Honduras.png",
  "Croatia": "Croatia.png",
  "Haiti": "Haiti.png",
  "Hungary": "Hungary.png",
  "Canary Islands": "Canary_Islands.png",
  "Indonesia": "Indonesia.png",
  "Ireland": "Ireland.png",
  "Israel": "Israel.png",
  "Isle of Man": "Isle_of_Man.png",
  "India": "India.png",
  "British Indian Ocean Territory": "British_Indian_Ocean_Territory.png",
  "Iraq": "Iraq.png",
  "Iran": "Iran.png",
  "Iceland": "Iceland.png",
  "Italy": "Italy.png",
  "Jersey": "Jersey.png",
  "Jamaica": "Jamaica.png",
  "Jordan": "Jordan.png",
  "Japan": "Japan.png",
  "Kenya": "Kenya.png",
  "Kyrgyzstan": "Kyrgyzstan.png",
  "Cambodia": "Cambodia.png",
  "Kiribati": "Kiribati.png",
  "Comoros": "Comoros.png",
  "St. Kitts and Nevis": "St._Kitts_&_Nevis.png",
  "North Korea": "North_Korea.png",
  "South Korea": "South_Korea.png",
  "Kuwait": "Kuwait.png",
  "Cayman Islands": "Cayman_Islands.png",
  "Kazakhstan": "Kazakhstan.png",
  "Laos": "Laos.png",
  "Lebanon": "Lebanon.png",
  "St. Lucia": "St._Lucia.png",
  "Liechtenstein": "Liechtenstein.png",
  "Sri Lanka": "Sri_Lanka.png",
  "Liberia": "Liberia.png",
  "Lesotho": "Lesotho.png",
  "Lithuania": "Lithuania.png",
  "Luxembourg": "Luxembourg.png",
  "Latvia": "Latvia.png",
  "Libya": "Libya.png",
  "Morocco": "Morocco.png",
  "Monaco": "Monaco.png",
  "Moldova": "Moldova.png",
  "Montenegro": "Montenegro.png",
  "St. Martin": "St._Martin.png",
  "Madagascar": "Madagascar.png",
  "Marshall Islands": "Marshall_Islands.png",
  "Macedonia": "Macedonia.png",
  "Mali": "Mali.png",
  "Myanmar (Burma)": "Myanmar_(Burma).png",
  "Mongolia": "Mongolia.png",
  "Macau SAR China": "Macau_SAR_China.png",
  "Northern Mariana Islands": "Northern_Mariana_Islands.png",
  "Martinique": "Martinique.png",
  "Mauritania": "Mauritania.png",
  "Montserrat": "Montserrat.png",
  "Malta": "Malta.png",
  "Mauritius": "Mauritius.png",
  "Maldives": "Maldives.png",
  "Malawi": "Malawi.png",
  "Mexico": "Mexico.png",
  "Malaysia": "Malaysia.png",
  "Mozambique": "Mozambique.png",
  "Namibia": "Namibia.png",
  "New Caledonia": "New_Caledonia.png",
  "Niger": "Niger.png",
  "Norfolk Island": "Norfolk_Island.png",
  "Nigeria": "Nigeria.png",
  "Nicaragua": "Nicaragua.png",
  "Netherlands": "Netherlands.png",
  "Norway": "Norway.png",
  "Nepal": "Nepal.png",
  "Nauru": "Nauru.png",
  "Niue": "Niue.png",
  "New Zealand": "New_Zealand.png",
  "Oman": "Oman.png",
  "Panama": "Panama.png",
  "Peru": "Peru.png",
  "French Polynesia": "French_Polynesia.png",
  "Papua New Guinea": "Papua_New_Guinea.png",
  "Philippines": "Philippines.png",
  "Pakistan": "Pakistan.png",
  "Poland": "Poland.png",
  "St. Pierre and Miquelon": "St._Pierre_&_Miquelon.png",
  "Pitcairn Islands": "Pitcairn_Islands.png",
  "Puerto Rico": "Puerto_Rico.png",
  "Palestinian Territories": "Palestinian_Territories.png",
  "Portugal": "Portugal.png",
  "Palau": "Palau.png",
  "Paraguay": "Paraguay.png",
  "Qatar": "Qatar.png",
  "R\u00e9union": "R\u00e9union.png",
  "Romania": "Romania.png",
  "Serbia": "Serbia.png",
  "Russia": "Russia.png",
  "Rwanda": "Rwanda.png",
  "Saudi Arabia": "Saudi_Arabia.png",
  "Solomon Islands": "Solomon_Islands.png",
  "Seychelles": "Seychelles.png",
  "Sudan": "Sudan.png",
  "Sweden": "Sweden.png",
  "Singapore": "Singapore.png",
  "St. Helena": "St._Helena.png",
  "Slovenia": "Slovenia.png",
  "Svalbard and Jan Mayen": "Svalbard_&_Jan_Mayen.png",
  "Slovakia": "Slovakia.png",
  "Sierra Leone": "Sierra_Leone.png",
  "San Marino": "San_Marino.png",
  "Senegal": "Senegal.png",
  "Somalia": "Somalia.png",
  "Suriname": "Suriname.png",
  "South Sudan": "South_Sudan.png",
  "S\u00e3o Tom\u00e9 and Pr\u00edncipe": "S\u00e3o_Tom\u00e9_&_Pr\u00edncipe.png",
  "El Salvador": "El_Salvador.png",
  "Sint Maarten": "Sint_Maarten.png",
  "Syria": "Syria.png",
  "Swaziland": "Swaziland.png",
  "Tristan da Cunha": "Tristan_da_Cunha.png",
  "Turks and Caicos Islands": "Turks_&_Caicos_Islands.png",
  "Chad": "Chad.png",
  "French Southern Territories": "French_Southern_Territories.png",
  "Togo": "Togo.png",
  "Thailand": "Thailand.png",
  "Tajikistan": "Tajikistan.png",
  "Tokelau": "Tokelau.png",
  "Timor-Leste": "Timor-Leste.png",
  "Turkmenistan": "Turkmenistan.png",
  "Tunisia": "Tunisia.png",
  "Tonga": "Tonga.png",
  "Turkey": "Turkey.png",
  "Trinidad and Tobago": "Trinidad_&_Tobago.png",
  "Tuvalu": "Tuvalu.png",
  "Taiwan": "Taiwan.png",
  "Tanzania": "Tanzania.png",
  "Ukraine": "Ukraine.png",
  "Uganda": "Uganda.png",
  "U.S. Outlying Islands": "U.S._Outlying_Islands.png",
  "United States": "United_States.png",
  "Uruguay": "Uruguay.png",
  "Uzbekistan": "Uzbekistan.png",
  "Vatican City": "Vatican_City.png",
  "St. Vincent and Grenadines": "St._Vincent_&_Grenadines.png",
  "Venezuela": "Venezuela.png",
  "British Virgin Islands": "British_Virgin_Islands.png",
  "U.S. Virgin Islands": "U.S._Virgin_Islands.png",
  "Vietnam": "Vietnam.png",
  "Vanuatu": "Vanuatu.png",
  "Wallis and Futuna": "Wallis_&_Futuna.png",
  "Samoa": "Samoa.png",
  "Kosovo": "Kosovo.png",
  "Yemen": "Yemen.png",
  "Mayotte": "Mayotte.png",
  "South Africa": "South_Africa.png",
  "Zambia": "Zambia.png",
  "Zimbabwe": "Zimbabwe.png"
}
